version: "3.8"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=${ACME_EMAIL:-your-email@example.com}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --api=true
      - --api.dashboard=true
      - --log.level=DEBUG
      - --accesslog=true
      - --accesslog.filepath=/var/log/traefik/access.log
      - --global.checkNewVersion=false
      - --global.sendAnonymousUsage=false
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./logs/traefik:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`${DOMAIN:-localhost}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api/dashboard`))"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-dashboard.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$lOz5ELjB$$QCiO7NJ.jEHh5Y5CygjRp/" # Username: admin, Password: admin
      - "traefik.http.middlewares.traefik-compression.compress=true"
      - "traefik.http.routers.traefik-dashboard.middlewares=traefik-compression,traefik-auth"
      - "traefik.http.routers.traefik-dashboard.priority=100"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betterhomepage
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - NODE_ENV=production
      - DOMAIN=${DOMAIN:-localhost}
      - NEXT_PUBLIC_APP_URL=https://${DOMAIN:-localhost}
      - PORT=3000
      - HOSTNAME=0.0.0.0
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${DOMAIN:-localhost}`) || Host(`www.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.web-compression.compress=true"
      - "traefik.http.routers.web.middlewares=web-compression"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - web

networks:
  web:
    name: web
    external: false
    driver: bridge
    enable_ipv6: true
