services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=rywoox@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --api=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  betterhomepage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betterhomepage
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports: # Uncomment for direct testing
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.betterhomepage.rule=Host(`home.rywoox.com`) || Host(`www.home.rywoox.com`)"
      - "traefik.http.routers.betterhomepage.entrypoints=websecure"
      - "traefik.http.routers.betterhomepage.tls.certresolver=myresolver"
      - "traefik.http.services.betterhomepage.loadbalancer.server.port=3000"

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - web

networks:
  web:
    driver: bridge
    enable_ipv6: true
